/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: hamsterholm (https://sketchfab.com/hamsterholm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hamster-e8f919fbff4f4b8ebb4384cfbc66d4f9
Title: Hamster
*/
import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.366}>
        <mesh
          geometry={
            nodes["hamster������������������_hamster������������������_0"]
              .geometry
          }
          material={materials.hamster}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
