"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pedal_board_ass_y.gltf 
*/
import { OrthographicCamera, useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/pedal_board_ass_y.gltf", true);

  // 디버깅: 모델 로딩 확인
  React.useEffect(() => {
    if (nodes && materials) {
      console.log("✅ Model loaded successfully:", {
        hasNodes: !!nodes,
        hasMaterials: !!materials,
        nodeCount: Object.keys(nodes).length,
        materialCount: Object.keys(materials).length,
      });

      // 첫 번째 노드의 바운딩 박스 확인
      const firstNode = Object.values(nodes)[0];
      if (firstNode?.geometry) {
        firstNode.geometry.computeBoundingBox();
        const box = firstNode.geometry.boundingBox;
        console.log("📦 First node bounding box:", {
          min: box.min,
          max: box.max,
          size: box.max.clone().sub(box.min),
        });
      }
    } else {
      console.warn("⚠️ Nodes or materials not loaded yet");
    }
  }, [nodes, materials]);

  if (!nodes || !materials) {
    return null;
  }

  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[4.041, 4.237, 4.213]}
        rotation={[-0.785, 0.616, 0.524]}
      />
      <group position={[0, 0.171, -0.095]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["MSBR-7-1"].geometry}
          material={nodes["MSBR-7-1"].material}
        />
        <mesh
          geometry={nodes["MSBR-5-1"].geometry}
          material={nodes["MSBR-5-1"].material}
        />
        <mesh
          geometry={nodes["MSBR-4-1"].geometry}
          material={nodes["MSBR-4-1"].material}
        />
        <mesh
          geometry={nodes["MSBR-1-1"].geometry}
          material={nodes["MSBR-1-1"].material}
        />
        <mesh
          geometry={nodes.mesh_25.geometry}
          material={nodes.mesh_25.material}
        />
        <mesh
          geometry={nodes.mesh_25_1.geometry}
          material={nodes.mesh_25_1.material}
        />
        <mesh
          geometry={nodes.mesh_30.geometry}
          material={nodes.mesh_30.material}
        />
        <mesh
          geometry={nodes.mesh_30_1.geometry}
          material={nodes.mesh_30_1.material}
        />
      </group>
      <group
        position={[-0.323, 0.14, -0.143]}
        rotation={[-2.009, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes["BY4-235_피스톤-1"].geometry}
          material={materials["color-4"]}
        />
        <group position={[0.064, 0, 0]} rotation={[Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.mesh_32.geometry}
            material={materials["color-9"]}
          />
          <mesh
            geometry={nodes.mesh_32_1.geometry}
            material={materials["color-10"]}
          />
        </group>
      </group>
      <group
        position={[-0.014, 0.184, -0.046]}
        rotation={[0.021, 0.895, -3.121]}
      >
        <group
          position={[-0.003, 0.002, 0.016]}
          rotation={[-0.017, -0.676, -0.048]}
        >
          <mesh
            geometry={nodes["파트6-1"].geometry}
            material={nodes["파트6-1"].material}
            position={[-0.006, -0.003, 0]}
          />
          <mesh
            geometry={nodes["BYODD30-S-HANDLE-1"].geometry}
            material={materials["color-5"]}
          />
          <mesh
            geometry={nodes["BYODD30-S-BODY-1"].geometry}
            material={materials["color-11"]}
            position={[0, -0.004, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-21"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.342, 0.176, -0.196]}
        rotation={[-Math.PI / 2, -0.252, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-38"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.348, 0.029, -0.081]}
        rotation={[-1.179, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-22"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.342, 0.16, -0.196]}
        rotation={[-Math.PI / 2, 0.394, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-27"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.342, 0.176, -0.196]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-35"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.348, 0.034, -0.063]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-36"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.348, 0.057, -0.069]}
        rotation={[-1.179, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-34"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.348, 0.053, -0.087]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-5"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.025, 0.169, -0.088]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-6"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.022, 0.198, -0.095]}
        rotation={[0, 1.429, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-25"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.342, 0.16, -0.196]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-8"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.022, 0.198, -0.095]}
        rotation={[0, 0.18, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-2"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.025, 0.169, -0.088]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-4"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.025, 0.169, -0.102]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-34"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.05, 0.111, -0.099]}
        rotation={[0, -1.077, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-3"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.025, 0.169, -0.102]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["MirrorSupport3-2"].geometry}
        material={materials["matte aluminum-2"]}
        position={[0.165, 0, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["MirrorVDL_Bracket-2"].geometry}
        material={materials["matte aluminum-3"]}
        position={[0.061, 0.068, -0.195]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["Stopper_대칭-3"].geometry}
        material={nodes["Stopper_대칭-3"].material}
        position={[0.342, 0.168, -0.187]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["byc-17-3-2"].geometry}
        material={materials["matte aluminum-1"]}
        position={[0.343, 0.067, 0.071]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["635mm_패널마운트-2"].geometry}
        material={materials["color-7"]}
        position={[0.345, 0.043, -0.075]}
        rotation={[-1.825, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["MirrorR02_Support_Block1-2"].geometry}
        material={materials["matte aluminum"]}
        position={[0.35, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes["C-HCDG5-15-1"].geometry}
        material={materials.color}
        position={[-0.35, 0.196, -0.182]}
      />
      <group position={[0, 0.207, -0.032]} rotation={[-Math.PI, 0, Math.PI]}>
        <mesh
          geometry={nodes.mesh_22.geometry}
          material={materials["pw-mt11120-9"]}
        />
        <mesh
          geometry={nodes.mesh_22_1.geometry}
          material={materials["pw-mt11120-9"]}
        />
      </group>
      <mesh
        geometry={nodes["by4-bk-16s-1"].geometry}
        material={materials["color-3"]}
        position={[-0.334, 0.124, -0.177]}
        rotation={[0.855, 0, Math.PI]}
      />
      <mesh
        geometry={nodes["635mm_패널마운트-1"].geometry}
        material={materials["color-7"]}
        position={[-0.345, 0.043, -0.075]}
        rotation={[1.316, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["upper_catch-6-1"].geometry}
        material={materials["color-8"]}
        position={[0, 0.171, -0.095]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-32"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.175, 0.043, 0.155]}
        rotation={[0.097, -0.084, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-18"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.15, 0.021, 0.191]}
        rotation={[-Math.PI / 2, -1.518, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-38"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.155, 0.109, -0.043]}
        rotation={[0, 0.001, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-21"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.18, 0.091, -0.191]}
        rotation={[Math.PI / 2, 1.557, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-23"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.15, 0.091, -0.191]}
        rotation={[-Math.PI / 2, 1.559, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-25"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.155, 0.109, -0.173]}
        rotation={[0, -0.013, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-26"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.175, 0.109, -0.173]}
        rotation={[0, -0.008, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-28"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.155, 0.109, -0.043]}
        rotation={[0, 0.022, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-30"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.175, 0.056, 0.025]}
        rotation={[0.097, -0.076, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-31"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.155, 0.043, 0.155]}
        rotation={[0.097, -0.083, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-17"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.18, 0.021, 0.191]}
        rotation={[Math.PI / 2, -1.568, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-19"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.18, 0.021, 0.191]}
        rotation={[-Math.PI / 2, -1.516, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-22"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.15, 0.091, -0.191]}
        rotation={[Math.PI / 2, 1.554, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-20"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.15, 0.021, 0.191]}
        rotation={[-Math.PI / 2, -1.501, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-29"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.155, 0.056, 0.025]}
        rotation={[0.097, -0.074, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-33"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.175, 0.043, 0.155]}
        rotation={[0.097, -0.085, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-35"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.175, 0.056, 0.025]}
        rotation={[0.097, -0.1, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-24"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.18, 0.091, -0.191]}
        rotation={[-Math.PI / 2, 1.565, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-36"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.155, 0.056, 0.025]}
        rotation={[0.097, -0.099, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-37"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.05, 0.112, -0.099]}
        rotation={[-Math.PI, -0.74, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-27"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.175, 0.109, -0.043]}
        rotation={[0, 0.016, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-34"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.155, 0.043, 0.155]}
        rotation={[0.097, -0.084, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-37"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.175, 0.109, -0.043]}
        rotation={[0, 0.003, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-39"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.175, 0.109, -0.173]}
        rotation={[0, -0.004, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-40"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.155, 0.109, -0.173]}
        rotation={[0, -0.014, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-5"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.115, -0.055]}
        rotation={[0, -0.678, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-4"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.116, -0.105]}
        rotation={[0, -1.008, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-8"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.098, -0.199]}
        rotation={[Math.PI / 2, -0.784, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-9"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.018, -0.197]}
        rotation={[Math.PI / 2, -0.597, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-2"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.115, -0.08]}
        rotation={[0, -1.012, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-1"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.115, -0.105]}
        rotation={[0, -0.088, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-10"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.115, -0.055]}
        rotation={[Math.PI, -1.366, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-11"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.098, -0.197]}
        rotation={[-Math.PI / 2, -0.306, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-7"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.013, 0.198]}
        rotation={[Math.PI / 2, -0.077, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-12"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.018, -0.198]}
        rotation={[-Math.PI / 2, -1.172, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-6"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.343, 0.033, 0.199]}
        rotation={[-Math.PI / 2, 0.885, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-13"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.033, 0.198]}
        rotation={[Math.PI / 2, 1.491, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-13"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.324, 0.157, -0.172]}
        rotation={[-1.179, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-14"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[-0.324, 0.125, -0.144]}
        rotation={[-1.179, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_iso-2"].geometry}
        material={materials["satin finish stainless steel-5"]}
        position={[-0.343, 0.046, 0.021]}
        rotation={[0, -1.281, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-16"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.115, -0.08]}
        rotation={[-Math.PI, -1.117, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-25"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.342, 0.111, -0.152]}
        rotation={[0, -0.681, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-42"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.343, 0.058, -0.198]}
        rotation={[-Math.PI / 2, -1.562, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-27"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.342, 0.112, -0.152]}
        rotation={[-Math.PI, -1.453, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_iso-1"].geometry}
        material={materials["satin finish stainless steel-5"]}
        position={[-0.343, 0.046, 0.121]}
        rotation={[0, -0.83, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_iso-4"].geometry}
        material={materials["satin finish stainless steel-5"]}
        position={[0.343, 0.046, 0.021]}
        rotation={[-Math.PI, 0.224, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-16"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.324, 0.125, -0.144]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-24"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[-0.342, 0.112, -0.124]}
        rotation={[0, -0.29, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-14"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.343, 0.013, 0.198]}
        rotation={[Math.PI / 2, -0.197, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_am-26"].geometry}
        material={materials["satin finish stainless steel"]}
        position={[0.342, 0.112, -0.179]}
        rotation={[0, -0.023, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-5"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[0.342, 0.112, -0.124]}
        rotation={[0, 0.032, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-6"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.342, 0.112, -0.179]}
        rotation={[0, -0.826, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_countersunk_head_screw_iso-41"].geometry}
        material={materials["satin finish stainless steel-4"]}
        position={[-0.343, 0.058, -0.198]}
        rotation={[-Math.PI / 2, -1.562, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_ks-15"].geometry}
        material={materials["satin finish stainless steel-2"]}
        position={[0.324, 0.157, -0.172]}
      />
      <mesh
        geometry={nodes["domed_cap_nut_ks-2"].geometry}
        material={materials["satin finish stainless steel-1"]}
        position={[-0.349, 0.197, -0.022]}
        rotation={[-0.039, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["VDL_Bracket-1"].geometry}
        material={materials["pw-mt11120-1"]}
        position={[-0.061, 0.068, -0.195]}
      />
      <mesh
        geometry={nodes["domed_cap_nut_ks-3"].geometry}
        material={materials["satin finish stainless steel-1"]}
        position={[0.349, 0.197, -0.022]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes["byc-17-3-1"].geometry}
        material={materials["matte aluminum-1"]}
        position={[-0.343, 0.067, 0.071]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["socket_head_cap_screw_iso-3"].geometry}
        material={materials["satin finish stainless steel-5"]}
        position={[0.343, 0.046, 0.121]}
        rotation={[0, 0.007, Math.PI / 2]}
      />
      <mesh
        geometry={nodes["Slide_Support-1"].geometry}
        material={materials["pw-mt11120-10"]}
        position={[0, 0.202, -0.038]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["BYODD30-S-LOCK-1"].geometry}
        material={materials["color-12"]}
        position={[0, 0.187, -0.065]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes["R02_Support_Block2_대칭-4"].geometry}
        material={materials["pw-mt11120-6"]}
        position={[0.342, 0.115, -0.137]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["MirrorC-HCDG5-15-2"].geometry}
        material={nodes["MirrorC-HCDG5-15-2"].material}
        position={[0.35, 0.196, -0.182]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes["by4-bk-16s-2"].geometry}
        material={materials["color-3"]}
        position={[0.334, 0.124, -0.177]}
        rotation={[-2.286, 0, 0]}
      />
      <mesh
        geometry={nodes["R03_Frame2-1"].geometry}
        material={materials["pw-mt11120-3"]}
        position={[0, 0.187, -0.1]}
        rotation={[-Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes["R02_Support_Block2-1"].geometry}
        material={materials["pw-mt11120-5"]}
        position={[-0.342, 0.115, -0.137]}
      />
      <mesh
        geometry={nodes["R02_Support_Block3-1"].geometry}
        material={materials["pw-mt11120-7"]}
        position={[0, 0.163, -0.092]}
      />
      <mesh
        geometry={nodes["Stopper-1"].geometry}
        material={materials["pw-mt11120-2"]}
        position={[-0.342, 0.168, -0.187]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes["Frame_Support-1"].geometry}
        material={materials["pw-mt11120-4"]}
        position={[-0.165, 0, 0]}
      />
      <mesh
        geometry={nodes["R03_Support_Block1-1"].geometry}
        material={materials["pw-mt11120-8"]}
        position={[-0.35, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes["VoodooLab_3+-1"].geometry}
        material={materials["color-2"]}
        position={[0, 0.069, -0.15]}
      />
      <mesh
        geometry={nodes.mesh_101.geometry}
        material={materials["pw-mt11120"]}
      />
      <mesh
        geometry={nodes.mesh_101_1.geometry}
        material={materials["pw-mt11120"]}
      />
    </group>
  );
}

useGLTF.preload("/pedal_board_ass_y.gltf", true);
